### Send POST request with json body
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "John",
  "lastName": "Doe",
  "birthDate": "01/01/1970",
  "email": "johndoe@localhost"
}

### GET all users
GET http://localhost:8080/users?birthDate.gt=01/01/1970&birthDate.lt=01/01/1971