spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clothes-shopping
    username: test
    password: culaso
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
